### ISSUE TITLE
Невозможно создать Donee

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#11]
Непонятно, почему невозможно создать Donee. После заполнения всех полей появляется вот такой экран:

![screen shot 2014-04-05 at 12 49 31 pm](https://cloud.githubusercontent.com/assets/4335901/2623622/23a8607a-bcfd-11e3-86e8-6d7ded36e59b.png)

**Comment by RealBerd** [comment]
Да, у меня тоже такое случилось. Мы разобирёмся почему это возникает.

**Comment by DmitrysIF** [comment]
Исправлено.

**Comment by DeveloperRegistry** [comment]
Tanya, please retest once the fix is deployed.

**Comment by Fetati** [comment]
Не работает!

**Comment by Fetati** [comment]
Tanya, please attach error message or screen shot.

**Comment by DmitrysIF** [comment]
Мне необходимо знать браузер, в котором это было обнаружено, какие поля были заполнены, были ли загружены картинки в галерею. В общем все, что поможет мне вопроизвести ошибку и отследить ее источник.

**Comment by DmitrysIF** [comment]
Ошибка локализована. Исправляется.

**Comment by Fetati** [comment]
Было обнаружено в Хроме. Все поля заполнены. Пыталась и с фото, и без фото. Никак не работает.

**Comment by DmitrysIF** [comment]
Попробуйте еще раз - я сделал обновление.

**Comment by Fetati** [comment]
Не работает в Chrome and Safari

**Comment by DeveloperRegistry** [comment]
Tanya, do you have any special characters such as apostrophes? I wonder if you could attach a screen shot with all fields populated?

**Comment by Fetati** [comment]
![screen shot 2014-04-08 at 8 47 17 pm](https://cloud.githubusercontent.com/assets/4335901/2651841/bbd511b0-bf99-11e3-991d-54d404d135a1.png)

**Comment by DeveloperRegistry** [comment]
Did you cut and paste the Description from HSTT website? I typed it in and it worked for me. However, when I cut and paste I got the following exception:

[Dima, this is for you. We may need to start stripping content from special characters, styles and fonts]
A potentially dangerous Request.Form value was detected from the client (contentdonee="...t-family: &#39;trebuchet MS&#3...").

Description: ASP.NET has detected data in the request that is potentially dangerous because it might include HTML markup or script. The data might represent an attempt to compromise the security of your application, such as a cross-site scripting attack. If this type of input is appropriate in your application, you can include code in a web page to explicitly allow it. For more information, see http://go.microsoft.com/fwlink/?LinkID=212874. 

Exception Details: System.Web.HttpRequestValidationException: A potentially dangerous Request.Form value was detected from the client (contentdonee="...t-family: &#39;trebuchet MS&#3...").

Source Error: 

Line 27:                 string DoneeSlug = Request.Form["doneeslug"];
Line 28:                 string TitleDonee = Request.Form["titledonee"];
Line 29:                 string ContentDonee = Request.Form["contentdonee"];
Line 30:                 string Location = Request.Form["location"];
Line 31:                 string ZIP = Request.Form["zip"];

Source File: c:\Users\Anton\Source\Workspaces\GOODdler\Dev\GOODdlerCloud\GOODdlerWeb\Controllers\DoneeController.cs    Line: 29 

Stack Trace: 

[HttpRequestValidationException (0x80004005): A potentially dangerous Request.Form value was detected from the client (contentdonee="...t-family: &#39;trebuchet MS&#3...").]
   System.Web.HttpRequest.ValidateString(String value, String collectionKey, RequestValidationSource requestCollection) +12322974
   System.Web.HttpValueCollection.Get(String name) +90
   GOODdlerWeb.Controllers.DoneeController.CreateDonee() in c:\Users\Anton\Source\Workspaces\GOODdler\Dev\GOODdlerCloud\GOODdlerWeb\Controllers\DoneeController.cs:29
   lambda_method(Closure , ControllerBase , Object[] ) +113
   System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters) +81
   System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +751
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +93
   System.Web.Mvc.Async.ActionInvocation.InvokeSynchronousActionMethod() +90
   System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__36(IAsyncResult asyncResult, ActionInvocation innerInvokeState) +45
   System.Web.Mvc.Async.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) +211
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +196
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +141
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +65
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3c() +189
   System.Web.Mvc.Async.<>c__DisplayClass45.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3e() +717
   System.Web.Mvc.Async.<>c__DisplayClass30.<BeginInvokeActionMethodWithFilters>b__2f(IAsyncResult asyncResult) +66
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +71
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +196
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +141
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +65
   System.Web.Mvc.Async.<>c__DisplayClass28.<BeginInvokeAction>b__19() +103
   System.Web.Mvc.Async.<>c__DisplayClass1e.<BeginInvokeAction>b__1b(IAsyncResult asyncResult) +330
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +71
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +196
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +73
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +58
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +90
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +188
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +196
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +73
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +50
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +68
   System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +60
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +85
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +196
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +73
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +50
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +58
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +60
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__4(IAsyncResult asyncResult, ProcessRequestState innerState) +93
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +188
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +196
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +73
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +50
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +58
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +59
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +606
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +288

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.34009
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3c()
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass45.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3e()
  InnerException:

**Comment by Fetati** [comment]
Да, я copy/paste текст в описание. 
Тогда это баг - люди не будут вручную вбивать длинные описания.

**Comment by DmitrysIF** [comment]
Да, я знаю на счет проблемы с "'trebuchet MS&#3...")." Проблема состоит в том, что визивиг-редактор преобразует некоторые символы в численное выражение типа #3...(somenumbers), что воспринимается детектором атак как потенциально опасное выражение, которое может нанести вред. 
Проблема с редактором решается.

**Comment by DmitrysIF** [comment]
Проверьте и закройте этот issue, если все нормально.
