### ISSUE TITLE
Credit Card page

### ISSUE THREAD

**Issue by galinafed** [Goodler/code#161]
![image](https://cloud.githubusercontent.com/assets/7177944/2848323/b968736c-d0bb-11e3-9259-aba039564828.png)
1. I thought due to the large fees we will not be accepting AmEx. ( i would go with not accepting it at the moment)
2. AmEx is the only card (as far as i know) has 4Digit CVC code. If we will not accept it, then we are ok. If we decide to accept it then we would need to allow 4 digit number in CVC box.

**Comment by DeveloperRegistry** [comment]
Galya, there is a separate version of the project for integration with Authorize.net. I am working on all credit card processing changes. I will see if I can remove Amex emblem from the page. The page will also look different since we added name and address. It will be added to the main project with 3-4 days.

**Comment by galinafed** [comment]
got it

**Comment by DeveloperRegistry** [comment]
Replaced with am Image w/out AMEX. Closing the issue.
