### ISSUE TITLE
Очень долго грузится первая страница!!! 20-30 секунд! 

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#285]
По-прежнему очень долго грузится первая страница!!! 20-30 секунд! 
Можно что-то с этим сделать? А то народ будет уходить, не дождавшись.

**Comment by DeveloperRegistry** [comment]
I believe there are two reasons:

1) static content (Java Scrpt, common images) is served from IIS. We need to move it to the NGINX server.  
2) Large images were stored as large images. They are converted to smaller images during initial load. Creating smaller image blobs should speed up the process.

I need to do performance analysis to confirm these theories. 

Both fixes are not trivial. They should take 2-3 weeks because these are major architectural changes.Most likely #2 will give us quicker and faster improvement. So, I will start there.

**Comment by Fetati** [comment]
ок, я тогда поменяю картинки на легкие. Может поможет.

**Comment by DeveloperRegistry** [comment]
This should help. Because re-coding this will take some time.

**Comment by DeveloperRegistry** [comment]
It is common that the very first person who hits the webpage after deployment experiences 20-30 second delay due to compilation of dynamic content. Tested the website with three different tools. Our average front page load time is about 2 seconds. We will work on speeding it up with adding hardware capacity and minimizing/compressing content.

http://tools.pingdom.com/fpt/#!/bInC1U/www.gooddler.com
www.gooddler.com
Tested from Dallas, Texas, USA on June 10 at 00:22:36
Page size
633.8kB
Load time
1.98s
Requests
28
Perf. grade
78/100

http://www.webpagetest.org/
        Document Complete   Fully Loaded
Load Time   First Byte  Start Render    DOM Elements    Time    Requests    Bytes In    Time    Requests    Bytes In
First View  2.285s  0.842s  1.993s  242 2.285s  29  660 KB  2.513s  29  773 KB
Repeat View 1.119s  0.768s  1.121s  242 1.119s  1   34 KB   1.119s  1   34 KB

Google Web Optimization Suggestions:
65 / 100 Suggestions Summary
Should Fix:
Enable compression
Compressing resources with gzip or deflate can reduce the number of bytes sent over the network.
Enable compression for the following resources to reduce their transfer size by 176KiB (73% reduction).
Compressing http://www.gooddler.com/Content/scripts/jquery-1.9.1.min.js could save 74.9KiB (68% reduction).
Compressing http://www.gooddler.com/Content/css/base.css could save 48.3KiB (79% reduction).
Compressing http://www.gooddler.com/Content/scripts/cart-for-each-page.js could save 20.7KiB (81% reduction).
Compressing http://www.gooddler.com/ could save 13.5KiB (82% reduction).
Compressing http://www.gooddler.com/Content/scripts/jcarousel.js could save 11.6KiB (70% reduction).
Compressing http://www.gooddler.com/Content/css/normalize-2.1.3.css could save 5.2KiB (70% reduction).
Compressing http://www.gooddler.com/Content/scripts/main.js could save 1.2KiB (73% reduction).
Compressing http://www.gooddler.com/Content/scripts/carousel.js could save 622B (64% reduction).
Hide details
Leverage browser caching
Setting an expiry date or a maximum age in the HTTP headers for static resources instructs the browser to load previously downloaded resources from local disk rather than over the network.
Leverage browser caching for the following cacheable resources:
http://www.gooddler.com/Content/css/base.css (expiration not specified)
http://www.gooddler.com/Content/css/carousel.css (expiration not specified)
http://www.gooddler.com/Content/css/layout.css (expiration not specified)
http://www.gooddler.com/Content/css/normalize-2.1.3.css (expiration not specified)
http://www.gooddler.com/…ontent/images/anim/round-orange16x16.gif (expiration not specified)
http://www.gooddler.com/Content/images/arrows.png (expiration not specified)
http://www.gooddler.com/Content/images/donate_small.png (expiration not specified)
http://www.gooddler.com/…ontent/images/icon-gooddler-blue_big.png (expiration not specified)
http://www.gooddler.com/Content/images/icon-gooddler-gray.png (expiration not specified)
http://www.gooddler.com/Content/images/icon-list_blue.png (expiration not specified)
http://www.gooddler.com/Content/images/icon-list_gray.png (expiration not specified)
http://www.gooddler.com/Content/images/logo_icon.png (expiration not specified)
http://www.gooddler.com/Content/images/logo_sign.png (expiration not specified)
http://www.gooddler.com/Content/images/logo_text.png (expiration not specified)
http://www.gooddler.com/Content/images/mygoodd_v3s.png (expiration not specified)
http://www.gooddler.com/Content/images/social.png (expiration not specified)
http://www.gooddler.com/Content/scripts/carousel.js (expiration not specified)
http://www.gooddler.com/Content/scripts/cart-for-each-page.js (expiration not specified)
http://www.gooddler.com/Content/scripts/jcarousel.js (expiration not specified)
http://www.gooddler.com/Content/scripts/jquery-1.9.1.min.js (expiration not specified)
http://www.gooddler.com/Content/scripts/main.js (expiration not specified)
https://gooddler.blob.core.windows.net/images/2cuafZ2jx5Mi/w292_h268.jpg (expiration not specified)
https://gooddler.blob.core.windows.net/images/8wHk6PzjxMiR/w292_h268.jpg (expiration not specified)
https://gooddler.blob.core.windows.net/images/9PS6twtiXOnp/w292_h268.jpg (expiration not specified)
https://gooddler.blob.core.windows.net/images/G7Sjlt6pSwmD/w292_h268.jpg (expiration not specified)
https://gooddler.blob.core.windows.net/images/KrviLod5BPDT/w292_h268.jpg (expiration not specified)
https://gooddler.blob.core.windows.net/images/ckRmCAlgKjSE/w292_h268.jpg (expiration not specified)
Hide details
Eliminate render-blocking JavaScript and CSS in above-the-fold content
Show how to fix
Consider Fixing:
Optimize images
Properly formatting and compressing images can save many bytes of data.
Optimize the following images to reduce their size by 34.9KiB (10% reduction).
Losslessly compressing https://gooddler.blob.core.windows.net/images/8wHk6PzjxMiR/w292_h268.jpg could save 9.1KiB (11% reduction).
Losslessly compressing https://gooddler.blob.core.windows.net/images/2cuafZ2jx5Mi/w292_h268.jpg could save 4.2KiB (7% reduction).
Losslessly compressing https://gooddler.blob.core.windows.net/images/KrviLod5BPDT/w292_h268.jpg could save 3.5KiB (7% reduction).
Losslessly compressing http://www.gooddler.com/Content/images/mygoodd_v3s.png could save 2.8KiB (87% reduction).
Losslessly compressing https://gooddler.blob.core.windows.net/images/G7Sjlt6pSwmD/w292_h268.jpg could save 2.5KiB (5% reduction).
Losslessly compressing https://gooddler.blob.core.windows.net/images/ckRmCAlgKjSE/w292_h268.jpg could save 2.1KiB (4% reduction).
Losslessly compressing https://gooddler.blob.core.windows.net/images/9PS6twtiXOnp/w292_h268.jpg could save 1.2KiB (4% reduction).
Losslessly compressing http://www.gooddler.com/Content/images/logo_icon.png could save 1.2KiB (66% reduction).
Losslessly compressing http://www.gooddler.com/Content/images/logo_text.png could save 1.2KiB (43% reduction).
Losslessly compressing http://www.gooddler.com/Content/images/social.png could save 1.1KiB (58% reduction).
Losslessly compressing http://www.gooddler.com/Content/images/icon-gooddler-gray.png could save 1.1KiB (78% reduction).
Losslessly compressing http://www.gooddler.com/Content/images/arrows.png could save 897B (34% reduction).
Losslessly compressing http://www.gooddler.com/Content/images/donate_small.png could save 854B (70% reduction).
Losslessly compressing http://www.gooddler.com/…ontent/images/icon-gooddler-blue_big.png could save 853B (55% reduction).
Losslessly compressing http://www.gooddler.com/Content/images/icon-list_blue.png could save 845B (87% reduction).
Losslessly compressing http://www.gooddler.com/Content/images/icon-list_gray.png could save 837B (87% reduction).
Losslessly compressing http://www.gooddler.com/Content/images/logo_sign.png could save 803B (27% reduction).
Hide details
Reduce server response time
In our test, your server responded in 0.54 seconds. There are many factors that can slow down your server response time. Please read our recommendations to learn how you can monitor and measure where your server is spending the most time.
Hide details
Minify JavaScript
Compacting JavaScript code can save many bytes of data and speed up downloading, parsing, and execution time.
Minify JavaScript for the following resources to reduce their size by 28.5KiB (21% reduction).
Minifying http://www.gooddler.com/Content/scripts/jquery-1.9.1.min.js could save 18.7KiB (18% reduction).
Minifying http://www.gooddler.com/Content/scripts/cart-for-each-page.js could save 9.3KiB (37% reduction).
Minifying http://www.gooddler.com/Content/scripts/main.js could save 554B (34% reduction).
Hide details
Minify CSS
Compacting CSS code can save many bytes of data and speed up download and parse times.
Minify CSS for the following resources to reduce their size by 22.8KiB (34% reduction).
Minifying http://www.gooddler.com/Content/css/base.css could save 17.3KiB (29% reduction).
Minifying http://www.gooddler.com/Content/css/normalize-2.1.3.css could save 5.5KiB (74% reduction).
Hide details
Minify HTML
Compacting HTML code, including any inline JavaScript and CSS contained in it, can save many bytes of data and speed up download and parse times.
Minify HTML for the following resources to reduce their size by 4.3KiB (27% reduction).
Minifying http://www.gooddler.com/ could save 4.3KiB (27% reduction).

**Comment by Fetati** [comment]
Works pretty fast

**Comment by DeveloperRegistry** [comment]
We are at 2 seconds load time for local (Bay Area) access. I am keeping the defect open to see if we can make it faster. I am adding logging to all key methods (about 50% done). Once it is implemented, we can see what functionality slows us down.
