### ISSUE TITLE
I can't sign in to my gooddler account /Chrome

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#298]
Почему-то не могу войти в мой эккаунт на Chrome. Причем, система не пишет, что не так, просто никуда не пускает, ничего не объясняя. Я уже даже пароль reset. Все равно не пускает.

![screen shot 2014-06-26 at 10 59 16 am](https://cloud.githubusercontent.com/assets/4335901/3402409/d48102b4-fd5b-11e3-9410-ab95bf75fb36.png)

**Comment by DeveloperRegistry** [comment]
Do you have Kaspersky Antivirus installed? I've seen it before on my computer. Simply rebooting worked for me. Try to reboot.

The security implementation is so bad, I am contemplating completely re-coding it: removing Stormpath and doing our own implementation.  

PS: once I add logging, I should be able to to establish the root cause by looking the logs. Presently, we are completely blind.

**Comment by Fetati** [comment]
I don't have Kaspersky Antivirus. :( Попробую перезагрузиться.

**Comment by Fetati** [comment]
На компе заработало.
Не работает в Safari на iPhone4
