### ISSUE TITLE
Price discrepancy for items added to the wishlist (Urgent)

### ISSUE THREAD

**Issue by galinafed** [Goodler/code#363]
We just found out that some of the items, when pasting link from Amazon to the wish list pick the lowest price when transferred to Gooddler. Nikita told us that it would search for an average price, that should not be lower than the price of the picked item.
Example: 
When i tried to add this item:
http://www.amazon.com/Silver-Bottle-Organza-Favor-6-5x15/dp/B005A106NU/ref=pd_bxgy_ac_img_z
![screenshot 29](https://cloud.githubusercontent.com/assets/7177944/4140489/949e40dc-33a5-11e4-8b38-7debbfa7583f.png)

to this list:
http://gooddler.com/Wishlist/Edit/5

Here is what it added:
![screenshot 30](https://cloud.githubusercontent.com/assets/7177944/4140531/191af9f4-33a6-11e4-945d-49d28ee5c6e3.png)

An item that has   $5 cost!

**Comment by DeveloperRegistry** [comment]
Confirmed that Item Id is parsed correctly. Te $5.00 price is in the fact the lowest price (there is a link below saying that available from several sellers for $5.00). Otherwise, the price is $9.15. Please confirm requirements: do we need to display the average between $5.00 and $9.15?

  LowestNewPrice
  <!Amount>500</Amount> 
  <!CurrencyCode>USD</CurrencyCode> 
  <!FormattedPrice>$5.00</FormattedPrice> 
  <!/LowestNewPrice>
  <!TotalNew>5</TotalNew> 
  <!TotalUsed>0</TotalUsed> 
  <!TotalCollectible>0</TotalCollectible> 
  <!TotalRefurbished>0</TotalRefurbished> 
  <!/OfferSummary>
 <!Price>
  <!Amount>915</Amount> 
  <!CurrencyCode>USD</CurrencyCode> 
  <!FormattedPrice>$9.15</FormattedPrice> 
  <!/Price>

**Comment by DeveloperRegistry** [comment]
Implemented the following solution. Get a List of all Amounts from Amazon XML Response. Set the Highest price as the price.

**Comment by galinafed** [comment]
I think it's best to put highest possible price for right now. I am trying to add this item right now, list price $299:
http://www.amazon.com/HS-65L-Compact-Reversible-Refrigerator-Freezer/dp/B0058ENUBO/ref=lh_ni_t?ie=UTF8&psc=1&smid=A6E4KVQD2C316
![screenshot 31](https://cloud.githubusercontent.com/assets/7177944/4172466/57d9fdbc-3549-11e4-9d9c-702ee0f690e8.png)
but it is adding as $150
http://gooddler.com/Wishlist/Edit/10004
![screenshot 32](https://cloud.githubusercontent.com/assets/7177944/4172472/698f82d4-3549-11e4-857c-2871145f4387.png)

**Comment by galinafed** [comment]
same thing if i add:
http://www.amazon.com/Seventh-Generation-Natural-Liquid-Unscented/dp/B00COZ64TK/ref=lh_ni_t?ie=UTF8&psc=1&smid=A235DNGKWE88C9
![screenshot 33](https://cloud.githubusercontent.com/assets/7177944/4172614/ab650326-354b-11e4-8ffd-70d0e2b05a93.png)

It adds as $3.98 http://gooddler.com/Wishlist/Edit/10004
![screenshot 34](https://cloud.githubusercontent.com/assets/7177944/4172620/c1104fdc-354b-11e4-85be-74b07c7b4c69.png)

**Comment by DeveloperRegistry** [comment]
We will research and address ASAP.

**Comment by DeveloperRegistry** [comment]
Conducted complete investigation. Established that Amazon data returned by the web service may differ from data displayed on web pages. The issue is described here:
http://stackoverflow.com/questions/12923080/why-is-itemlookup-not-returning-any-price-information-even-when-requesting-all-3/13871309#13871309‏
"Unfortunately, you cannot count on consistency with AWS API. I've been dealing with this problem for almost two years. The problem is: even though the price is visible on the product (HTML) page, it is not guaranteed that it is available on the repository used by AWS API. You'll have to accept that fact if you want to continue to use their API"

Discussed the issue with Tanya. Coded a Price Override for Admin Users. Admins can now change prices as needed. Added a parameter to the database to capture the fact that price was manually updated. It will be used for Price Comparison Batch job.
