### ISSUE TITLE
Search of goods - wrong price (Walmart)

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#543]
Я добавляю товар - crayon

<img width="995" alt="screen shot 2017-06-07 at 4 03 22 pm" src="https://user-images.githubusercontent.com/4335901/26915981-3f92029c-4bdd-11e7-98c0-6102a29a0b9f.png">

Выбрала первый - цена 4.59
<img width="1046" alt="screen shot 2017-06-07 at 4 00 38 pm" src="https://user-images.githubusercontent.com/4335901/26916017-5ebf58e0-4bdd-11e7-9e11-f79772f61db6.png">

Тот же самы товар (зашла по линку) в Walmart стоит дороже:

<img width="1431" alt="screen shot 2017-06-07 at 4 00 25 pm" src="https://user-images.githubusercontent.com/4335901/26916044-7dd9af14-4bdd-11e7-8438-48decb745f1f.png">

Протестировала остальные товары в этом ряду - на 2 товара тоже цены дороже, а 2 столько же, сколько и в Walmart. 
Мы планировали добавлять 10% налогов сразу, так?

**Comment by DmitrysIF** [comment]
@Fetati это странная ситуация и такого быть не должно. Попробую спросить Сергея.

**Comment by sergchuv** [comment]
Item search retrieves "salePrice" instead of msrp. 
public class ResponseItem
    {
        public int ItemId;
        public int ParentItemId;
        public string Name;
        **public double SalePrice**
        public string CategoryPath;
        public string ShortDescription;
        public string LongDescription;
        public string ThumbnailImageUrl;
        public string MediumImageUrl;
        public string LargeImageUrl;
        public string ProductTrackingUrl;
        public double StandardShipRate;
        public bool MarketPlace;
        public string ProductUrl;
        public string CategoryNode;
        public bool Bundle;
        public bool AvailableOnline;
    }

This is fragment of the JSON response for that item.
....
  "msrp": 6.06,
  "salePrice": 4.59,
...

I suggest Dmirty change his code to show msrp. Variations API currently retrieves "msrp" and ignores "salePrice"

**Comment by sergchuv** [comment]
Changeset 637 fixes the issue.  
Explanation:
Walmart API responses price fields vary from item to item. The rule is that it contains at least one of two prices "msrp" and "salePrice", sometimes both. Currently, our site's logic is:

**if "msrp" exist use "msrp" otherwise use "salePrice"**

Walmart's web site logic may show one of these two price choices based on some other data. As the result, Goodlers price will be frequently higher than shown on Walmart site.

**Comment by DmitrysIF** [comment]
Немножко доработано, теперь всегда будет выбираться Максимальная цена из выдачи.
